version: '3.8'

services:
  # postgres:
  #   image: postgres:12.2
  #   environment: 
  #     - POSTGRES_PASSWORD=muysecure
    # TODO: set a volume
  # nginx:
    # image: nginx:1.22.1
  # node/express server
  server:
    build:
      context: ./server/
    command: /app/node_modules/.bin/nodemon src/index.ts
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  # React app
  frontend:
     build:
       context: ./ui/
       dockerfile: Dockerfile
     volumes:
       - ./ui/:/app
       - /app/node_modules
     ports:
       - "3000:3000"
     environment:
       - CHOKIDAR_USEPOLLING=true