version: '3.8'

services:
  # postgres:
  #   image: postgres:12.2
  #   environment: 
  #     - POSTGRES_PASSWORD=muysecure
    # TODO: set a volume
  # nginx:
    # image: nginx:1.22.1
  # TODO: node/express server
  # React app
  frontend:
     build:
       context: ./ui/
       dockerfile: Dockerfile
     volumes:
       - ./ui/:/app
       - /app/node_modules
     ports:
       - "3000:3000"
     environment:
       - CHOKIDAR_USEPOLLING=true