name: Build and Push Docker Image

# TODO: Make this workflow run only on changes to /server
on:
  push:
    paths:
      - "server/**"

# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: 'Image version'
#         required: true

env:
  REGISTRY: "registry.digitalocean.com/lgm-registry"
  IMAGE_NAME: "omniscrape-api:latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    env:
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build latest
        run: docker build --build-arg DATABASE_URL=$DATABASE_URL -t $(echo $REGISTRY)/$(echo $IMAGE_NAME) -f Dockerfile.prod .

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_PASSWORD }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      # TODO: Make this work
      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push to Digital Ocean Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME)
