name: Deploy UI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build static files
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Copy static files
        run: scp -r build/ ${{ secrets.SSH_USERNAME }}@${{ SSH_HOST }}:/var/www/app/ui

      - name: Restart nginx
        uses: appleboy/ssh-action@master
        with:
          host: droplet_ip
          username: user
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            sudo service nginx restart
