name: Prisma Migrate

on:
  push:
    branches: [main]
    paths:
      - "./server/prisma/**/*.*"
  workflow_dispatch:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"

      - name: Install
        run: npm install

  generate:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"

      - name: Install
        run: npm install

      - run: rm -rf node_modules/.prisma

      - name: Generate Prisma Client
        run: npx prisma generate

  migrate:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 19.x
          cache: "npm"

      - name: Install
        run: npm install

      - run: rm -rf node_modules/.prisma

      - name: Deploy Migrations
        run: npx prisma migrate deploy --schema=./server/prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
